### ISSUE TITLE
Esemeny reszletes oldala

### ISSUE THREAD

**Issue by fzsoca** [kir-dev/schorpong#1]
Esemeny oldalon, ha megnezunk egy csapatot majd boneszo back gombjaval visszamegyunk egy oldalt, a kommentelos resz egyre lejjebb kerul (mintha ahanyadszorra visszamegyunk, annyiszor kihagyna a helyet a csapatoknak)

Plus minor dolog: Jelentkezése határidő van írva, jelentkezési határidő helyett.

**Comment by kiralybalint** [comment]
Eltávolítottam a komment rendszert, mert látszólag nem volt rá igény a felhasználóktól (talán a jövőben csinálunk saját rendszert, aminek nagyobb sikere lesz).
Időközben a typo is javítva lett.
